language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
 
  - pear channel-discover pear.phpqatools.org
  - pear install -f phpqatools/phpqatools
  - phpenv rehash
  
  - mysql -e 'create database fabrikar_ci;'
  - mysql fabrikar_ci < fabrik_build/tests/suites/database/stubs/mysql.sql

script:
  ant travis-phpcs

branches:
  only:
    - joomla3